export const ALERT = {
  SET_ALERT: 'SET_ALERT',
  REMOVE_ALERT: 'REMOVE_ALERT',
}

export const API_LOADING = 'API_LOADING'

export const AUTH = {
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILED: 'REGISTER_FAILED',
  USER_LOADED: 'USER_LOADED',
  AUTH_ERROR: 'AUTH_ERROR',
  LOGIN_SUCCESS: 'LOGIN_SUCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGOUT_USER: 'LOGOUT_USER',
}

export const PROFILE = {
  GET_PROFILE: 'GET_PROFILE',
}
